export { default as Users } from './users.svg';
export { default as Location } from './location.svg';
export { default as Coins } from './coins.svg';
export { default as ManageLists } from './manage_lists.svg';
export { default as Contact } from './contact.svg';
export { default as Inventory } from './inventory.svg';
export { default as Sales } from './sales.svg';
export { default as Purchases } from './purchases.svg';
export { default as Transfers } from './transfers.svg';
export { default as Despatch } from './despatch.svg';
export { default as UserFields } from './user_fields.svg';
export { default as Barcode } from './barcode.svg';
export { default as Company } from './company.svg';
export { default as SecurityLock } from './security_lock.svg';
export { default as Adaptors } from './adaptors.svg';
export { default as Pos } from './pos.svg';
export { default as About } from './about.svg';
export { default as OpenEye } from './open_eye.svg'
export { default as ClosedEye } from './closed_eye.svg'
export { default as Check } from './check.svg'
export { default as Cross } from './cross.svg'
export { default as Gear } from './gear.svg'
export { default as Plus } from './plus.svg'
export { default as Question } from './question.svg'
export { default as Search } from './search.svg'
export { default as RightArrow } from './right_arrow.svg'
export { default as RightArrow2 } from './right_arrow2.svg'
export { default as LeftArrow2 } from './left_arrow2.svg'